repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/dotnet/format
    rev: "v8.0.453106"
    hooks:
      - id: dotnet-format
        name: dotnet format
        language: dotnet
        types_or: ["c#", "vb"]
        entry: dotnet-format --include

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: dotnet-test
        name: Run C# Tests
        entry: dotnet test --verbosity normal
        language: system
        always_run: true
        pass_filenames: false
