name: Test and Deploy Playwright Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      # Playwrightパッケージを追加
      - name: Add Playwright package
        run: |
          cd HotelPlaywrightTests  # プロジェクトディレクトリに移動
          dotnet add package Microsoft.Playwright

      # プロジェクトのビルド
      - name: Build the project
        run: |
          cd HotelPlaywrightTests
          dotnet build

      # Playwrightブラウザのインストール
      - name: Install Playwright browsers
        run: |
          cd HotelPlaywrightTests
          pwsh bin/Debug/net8.0/playwright.ps1 install

      # Playwrightテストの実行
      - name: Run Playwright tests
        run: |
          cd HotelPlaywrightTests
          dotnet test --logger:html --results-directory docs/

      # テスト結果をindex.htmlにリネーム
      - name: Rename report to index.html
        run: |
          cd HotelPlaywrightTests
          mv docs/TestResults/*.html docs/index.html

      # 生成されたレポートをコミットしてプッシュ
      - name: Commit and push changes
        run: |
          cd HotelPlaywrightTests
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Add Playwright report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
