name: Test and Deploy Playwright Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build

      - name: Install Playwright browsers
        run: dotnet tool run playwright install # Playwrightのブラウザをインストール

      - name: Run Playwright tests
        run: dotnet test --logger:trx --results-directory TestResults

      # ReportGeneratorをインストール
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      # TRXをHTMLに変換
      - name: Generate HTML Report from TRX
        run: reportgenerator -reports:TestResults/*.trx -targetdir:TestResults/Report -reporttypes:Html

      - name: Create docs folder if not exists
        run: mkdir -p docs # docsフォルダがない場合に作成

      # docsフォルダを作成し、HTMLレポートを移動
      - name: Create docs folder and move report
        run: |
          mkdir -p docs
          mv TestResults/Report/* docs/

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Add Playwright report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
