name: Test and Deploy Playwright Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      # Playwrightパッケージの追加
      - name: Add Playwright package
        run: dotnet add package Microsoft.Playwright

      # プロジェクトのビルド
      - name: Build the project
        run: dotnet build

      # Playwrightブラウザのインストール
      - name: Install Playwright browsers
        run: playwright install

      - name: Run Playwright tests
        run: dotnet test --logger:html --results-directory docs/

      - name: Rename report to index.html
        run: mv docs/TestResults/*.html docs/index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Add Playwright report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
