name: Test and Deploy Playwright Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build

      # Playwrightブラウザのインストールを.NETツールで実行
      - name: Install Playwright browsers
        run: dotnet tool run playwright install # Playwrightのブラウザをインストール

      - name: Create docs folder if not exists
        run: mkdir -p docs # docsフォルダがない場合に作成

      # Playwrightテストの実行とHTMLレポート生成
      - name: Run Playwright tests and generate report
        run: dotnet test --logger:html --results-directory docs/ # テスト結果を指定ディレクトリに出力

      - name: Rename report to index.html
        run: mv docs/TestResults/*.html docs/index.html # レポートの名前をindex.htmlに変更

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Add Playwright report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
