name: Playwright Tests and Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # .NETのセットアップ
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      # プロジェクトのビルド
      - name: Build the project
        run: dotnet build

      # Playwrightブラウザのインストール
      - name: Install Playwright browsers
        run: pwsh bin/Debug/net8.0/playwright.ps1 install--with-deps

      # Playwrightテストの実行
      - name: Run Playwright tests
        run: dotnet test --logger:html --results-directory docs/

      # テスト結果をindex.htmlにリネーム
      - name: Rename report to index.html
        run: mv docs/TestResults/*.html docs/index.html

      # テスト結果のアップロード（失敗時）
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: HotelPlaywrightTests/docs/index.html

      # 生成されたレポートをコミットしてプッシュ
      - name: Commit and push changes
        working-directory: HotelPlaywrightTests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Add Playwright report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
