name: test-run-report-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write # GitHub Pagesにファイルを書き込む権限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Install dependencies
        run: |
          echo '{}' > package.json
          npm install @playwright/test@latest

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Create docs folder if not exists
        run: mkdir -p docs # docsフォルダがない場合に作成

      - name: Move report to docs
        run: mv playwright-report/* docs/

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Add Playwright report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
